name: Jetpack Compose Desktop CI

on:
  push:
    branches: [ master ]

jobs:
  build:
  
    strategy:
      matrix:
        os: [ 'macos-latest', 'windows-latest' ]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Create package
      run: ./gradlew package

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: distributable-${{ matrix.os }}
        if-no-files-found: ignore
        path: |
          build/**/*.dmg
          build/**/*.msi
   
    - name: Release
      uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
      with:
        prerelease: ${{ contains(github.event.inputs.version, '-rc') || contains(github.event.inputs.version, '-b') || contains(github.event.inputs.version, '-a') }}
        files: |
          build/**/*.dmg
          build/**/*.msi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
